# Generated by Django 5.0.4 on 2024-04-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=40)),
                ('player', models.CharField(blank=True, max_length=40, null=True)),
                ('room_code', models.CharField(max_length=10)),
                ('is_over', models.BooleanField(default=False)),
            ],
        ),
    ]
